### ISSUE TITLE
USB replacement wiki

### ISSUE THREAD

**Issue by Kermitdk** [rfrht/FT991A-PAT#18]
Hi
It look like there are images missing in  the description regarding replacing the main USB controller.

br
Claus

**Comment by rfrht** [comment]
Hi there Claus,

The images resides in my personal web server - which is shutdown for the last month and half, due to the construction in my apartment. 

It will be back (hopefully) in a month from now!

Will leave this Issue open and close when it is back online. Thanks for the interest; and if you need some specific information please get in touch; I'll be more than happy to help.

- RF.

**Comment by Kermitdk** [comment]
Hi again :-)
WOW that was a quick response 👍 
Well, I have just ordered the FT-991A hope it will arrive before the weekend. I will do the modification at some point, but just wanted to prepare myself for the replacement job og the controller, and how to make the connections to the extra port :-).

br
Claus

**Comment by rfrht** [comment]
Hope you enjoy your 991A as I enjoy mine!!!

A personal note, Claus

It's been almost three years since I did the mod, and works perfectly. I hope you have seen the video where I test for any sensitivity loss (spoiler: there were none), and will tell you what; it is **great** to work HF bands with the panadapter. A breeze.

I also took care to isolate completely the SDR during transmit mode and I am pending receive the Revision R board and components - which should arrive by the next month too

As of now I would not suggest you building or preparing the board: Give me some time so I can test it - and will publish the thorough test results!

**Comment by Kermitdk** [comment]
I will then be patient and wait for your great work :-) Yes, it difficult to get parts at the moment. But I guess I will also be busy getting to know the radio first ;-)

**Comment by Manawyrm** [comment]
Hi, 

@rfrht 
> pending receive the Revision R board

Any recommendations whether I should order the Revision R or the current Revision Q? 
I'm not afraid of a little SMD rework or modding, just mainly wanted to know how big the difference is and if it's worth the "risk" of ordering the new one. 

Thanks!

**Comment by rfrht** [comment]
> Any recommendations whether I should order the Revision R or the current Revision Q?

Hello, Tobias!

Go for Rev. R! The [Changelog](https://github.com/rfrht/FT991A-PAT/blob/Rev-R-Full/CHANGELOG.md) is far from being risky. The 2SC5086 and J310 were fed by resistive drops - Just got rid of them and is now making use of the existing power lines.

I procured the components in September, and it just didn't get delivered here in Brazil. Bought it again a couple of days ago, delivered to a Brazilian friend in NYC (PY2UGO) and will have the parts by the second half of January, when friend gets back to Brazil.

Then will post the test results and make Rev. R the current one.

Feel free to reach if you have any questions!

**Comment by rfrht** [comment]
> It will be back (hopefully) in a month from now!

Will tentatively bring back my home server this Sunday - fingers crossed!

**Comment by Manawyrm** [comment]
Awesome, thank you for the quick response!
I'll go buy some parts then :)

Happy new year,
Tobias

**Comment by rfrht** [comment]
> Hi It look like there are images missing in the description regarding replacing the main USB controller.
> 
> br Claus

Hello @Kermitdk @Manawyrm 

**Finally** I got my home server back, after long 5 months! The images are now rendering correctly.
